spring.application.name=reptrack

spring.datasource.url=jdbc:postgresql://localhost:5432/reptrack_dev
spring.datasource.username=ansh
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true