package com.reptrack;

import org.springframework.data.jpa.repository.JpaRepository;

/**
 * Provides database access for Member entities.
 * Extending JpaRepository provides findById(), findAll(), save(), delete() generated by 
 * Spring.
 *
 * <Member, String> means: this repository manages Member entities, and the primary key 
 * type is String (matches bioguideId).
 */
public interface MemberRepository extends JpaRepository<Member, String> {
}