package com.trackthehill;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;

/**
 * Provides database access for Member entities.
 * Extending JpaRepository provides findById(), findAll(), save(), delete()
 * generated by
 * Spring.
 *
 * <Member, String> means: this repository manages Member entities, and the
 * primary key
 * type is String (matches bioguideId).
 */
public interface MemberRepository extends JpaRepository<Member, String> {
    @Query("SELECT DISTINCT m.state FROM Member m ORDER BY m.state")
    List<String> findDistinctStates();

    List<Member> findByStateOrderByChamberAscDistrictAsc(String state);

    List<Member> findByChamberAndFirstNameContainingIgnoreCaseOrChamberAndLastNameContainingIgnoreCase(
            String chamber1, String firstName, String chamber2, String lastName);
}